apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-12-08T12:24:52Z"
  generation: 1
  labels:
    app: testmmc
  name: testmmc
  namespace: default
  resourceVersion: "1408"
  uid: 544c924e-dd4b-4430-8802-2d4be324eab8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: testmmc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testmmc
    spec:
      containers:
        - image: memoclap:2
          imagePullPolicy: Always
          name: memoclap
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
    - lastTransitionTime: "2021-12-08T12:24:52Z"
      lastUpdateTime: "2021-12-08T12:24:52Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2021-12-08T12:34:53Z"
      lastUpdateTime: "2021-12-08T12:34:53Z"
      message: ReplicaSet "testmmc-6bd8f98cd7" has timed out progressing.
      reason: ProgressDeadlineExceeded
      status: "False"
      type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
