---
- hosts: all
  remote_user: kube
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Create containerd config file
      file:
        path: "/etc/modules-load.d/containerd.conf"
        state: "touch"

    - name: installer ufw
      apt:
        name: ufw

    - name: TASK 2 Stop and Disable firewall
      shell: sudo systemctl disable --now ufw

    - name: TASK 3 Enable and Load Kernel modulesmodprobe Add conf for containerd
      blockinfile:
        path: "/etc/modules-load.d/containerd.conf"
        block: |
          overlay
          br_netfilter

# modprobe n'existe pas dans des containers (car sa sappuye sur le kernel qui est mon host)
#    - name: TASK 3 Enable and Load Kernel modulesmodprobe
#      shell: |
#        sudo modprobe overlay
#        sudo modprobe br_netfilter


    - name: TASK 4 Add Kernel settings Set system configurations for Kubernetes networking
      file:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        state: "touch"

    - name: Add conf for containerd
      blockinfile:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply new settings
      command: sudo sysctl --system

#    - name: TASK 5 Install containerd runtime nstall containerd
#      shell: |
#        sudo apt-get update && sudo apt-get install -y containerd
#        sudo mkdir -p /etc/containerd
#        sudo containerd config default | sudo tee /etc/containerd/config.toml
#        sudo systemctl restart containerd
#        sudo systemctl enable containerd

    - name: TASK 1 Disable and turn off SWAP disable swap
      shell: |
         sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
         sudo swapoff -a
    #        sudo sed -i '/swap/d' /etc/fstab


    - name: TASK 6 Add apt repo for kubernetes install and configure dependencies
      shell: |
        sudo apt-get update && sudo apt-get install -y apt-transport-https curl
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

    - name: Create kubernetes repo file
      file:
        path: "/etc/apt/sources.list.d/kubernetes.list"
        state: "touch"

    - name: Add K8s Source
      blockinfile:
        path: "/etc/apt/sources.list.d/kubernetes.list"
        block: |
          deb https://apt.kubernetes.io/ kubernetes-xenial main
#       on aurait aussi pur faire en shell:
#       curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - >/dev/null 2>&1
#       puis
#       apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main" >/dev/null 2>&1

    - name: TASK 7 Install Kubernetes components (kubeadm, kubelet and kubectl) install kubernetes
      shell: |
            sudo apt-get update
            sudo apt-get install -y kubelet=1.22.0-00 kubeadm=1.22.0-00 kubectl=1.22.0-00
            sudo apt-mark hold kubelet kubeadm kubectl
        
        
