version: "3.3"
services:
  proflib-comptes:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: proflib-compte:1
    container_name: proflib-compte
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - proflibcomptesdb
    restart: "always"
  proflibcomptesdb:
    ports:
      - 3306:3306
    container_name: proflibcomptesdb
    environment:
      - MYSQL_ROOT_PASSWORD=chenlaouche
      - MYSQL_DATABASE=proflibcomptesdb
    image: mariadb:latest
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - type: bind
#${root}
        source: /home/laurent/Documents/ProfChinoisLib2/mysqlaeffacer
        target: /var/lib/mysql
    restart: "always"
